  name: Waka Readme

  on:
    schedule:
      # Runs at 12am IST
      - cron: "0 */2 * * *"
    workflow_dispatch:
  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            COMMIT_BY_ME: True
            COMMIT_MESSAGE: ":)"
            SHOW_DAYS_OF_WEEK: True
            SHOW_LANGUAGE: True
            SHOW_PROJECTS: True
            SHOW_TIMEZONE: True
            SHOW_EDITORS: True
            SHOW_LOC_CHART: True
            SHOW_UPDATE_DATE: True
            SHOW_TOTAL_CODE_TIME: True
