name: Waka Readme

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART : "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: TRUE
          SHOW_LANGUAGE: TRUE
          SHOW_LINES_OF_CODE: TRUE
          SHOW_TIMEZONE: TRUE
          SHOW_EDITORS: TRUE
          SHOW_DAYS_OF_WEEK: TRUE
          SHOW_COMMIT: TRUE
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: 1
