name: Waka Readme

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: True
          SHOW_UPDATED_DATE: True
          COMMIT_MESSAGE: "Updated readme statistics"
          COMMIT_BY_ME: True
          LOCALE: "en"
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: True
          SHOW_TIMEZONE: True
          SHOW_PROJECTS: TRUE
          SHOW_LANGUAGE: TRUE
          SHOW_EDITORS: TRUE
          SHOW_DAYS_OF_WEEK: TRUE
